site_name: youtube

repo_name: youtube
repo_url: https://github.com/raghugolla/youtube.git

site_url: https://github.com/raghugolla/youtube.git
site_description: A baseline starting point for python projects
site_author: Raghu Golla

theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'Teal'

markdown_extensions:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - markdown.extensions.def_list
