name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.AUTO_APPROVE_PR_TOKEN }}
        stale-pr-message: 'This PR is stale due to inactivity for a long time. It will be closed shortly. To avoid that act on this'
        stale-pr-label: 'no-pr-activity'
        days-before-stale: 8
        days-before-close: 2
